-- Create artifacts table for Vercel Chat SDK integration
-- This table stores all artifacts generated by the AI chat system

-- Create enum for artifact types
CREATE TYPE artifact_type AS ENUM ('chat', 'document', 'code', 'image', 'other');

-- Create artifacts table
CREATE TABLE IF NOT EXISTS artifacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    type artifact_type NOT NULL DEFAULT 'other',
    content JSONB NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    ai_context JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX idx_artifacts_user_id ON artifacts(user_id);
CREATE INDEX idx_artifacts_type ON artifacts(type);
CREATE INDEX idx_artifacts_created_at ON artifacts(created_at DESC);
CREATE INDEX idx_artifacts_user_type ON artifacts(user_id, type);
CREATE INDEX idx_artifacts_ai_context ON artifacts USING GIN (ai_context);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_artifacts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
CREATE TRIGGER trigger_update_artifacts_updated_at
    BEFORE UPDATE ON artifacts
    FOR EACH ROW
    EXECUTE FUNCTION update_artifacts_updated_at();

-- Enable Row Level Security
ALTER TABLE artifacts ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Policy: Users can view their own artifacts
CREATE POLICY "Users can view own artifacts"
    ON artifacts
    FOR SELECT
    USING (auth.uid() = user_id);

-- Policy: Users can insert their own artifacts
CREATE POLICY "Users can insert own artifacts"
    ON artifacts
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own artifacts
CREATE POLICY "Users can update own artifacts"
    ON artifacts
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own artifacts
CREATE POLICY "Users can delete own artifacts"
    ON artifacts
    FOR DELETE
    USING (auth.uid() = user_id);

-- Create a view for artifact statistics
CREATE OR REPLACE VIEW artifact_stats AS
SELECT 
    user_id,
    type,
    COUNT(*) as count,
    MAX(created_at) as last_created
FROM artifacts
GROUP BY user_id, type;

-- Grant access to the view
GRANT SELECT ON artifact_stats TO authenticated;

-- Add comments for documentation
COMMENT ON TABLE artifacts IS 'Stores artifacts generated by the Vercel Chat SDK AI system';
COMMENT ON COLUMN artifacts.id IS 'Unique identifier for the artifact';
COMMENT ON COLUMN artifacts.user_id IS 'Reference to the user who owns this artifact';
COMMENT ON COLUMN artifacts.title IS 'Title or name of the artifact';
COMMENT ON COLUMN artifacts.description IS 'Brief description of the artifact content';
COMMENT ON COLUMN artifacts.type IS 'Type of artifact: chat, document, code, image, or other';
COMMENT ON COLUMN artifacts.content IS 'The actual content of the artifact stored as JSONB';
COMMENT ON COLUMN artifacts.metadata IS 'Additional metadata about the artifact';
COMMENT ON COLUMN artifacts.ai_context IS 'AI context including model, agent, and parameters used';
COMMENT ON COLUMN artifacts.created_at IS 'Timestamp when the artifact was created';
COMMENT ON COLUMN artifacts.updated_at IS 'Timestamp when the artifact was last updated';
