-- Add suggestions column to research_artifacts table
ALTER TABLE research_artifacts 
ADD COLUMN IF NOT EXISTS suggestions JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN research_artifacts.suggestions IS 'List of suggested follow-up questions generated by AI';
